// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwDHlQNVCLNjSnKf_zhURQE-mayxEmT0',
    appId: '1:555174955426:web:9b2f7dcb86963218cd8afb',
    messagingSenderId: '555174955426',
    projectId: 'cw-06-b37ce',
    authDomain: 'cw-06-b37ce.firebaseapp.com',
    storageBucket: 'cw-06-b37ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDDNGYXSnPr1S57pySvuckn4gCOPqIDI',
    appId: '1:555174955426:android:5b90d6f1cf9ba91dcd8afb',
    messagingSenderId: '555174955426',
    projectId: 'cw-06-b37ce',
    storageBucket: 'cw-06-b37ce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwDHlQNVCLNjSnKf_zhURQE-mayxEmT0',
    appId: '1:555174955426:web:175f300eed5ab831cd8afb',
    messagingSenderId: '555174955426',
    projectId: 'cw-06-b37ce',
    authDomain: 'cw-06-b37ce.firebaseapp.com',
    storageBucket: 'cw-06-b37ce.firebasestorage.app',
  );
}
